### ISSUE TITLE
добавить поле approved в объекте животного

### ISSUE THREAD

**Issue by ChalyaYM** [Popov-Dmitriy-Ivanovich/cow_backend#20]
в возвращаемый объект /cows/filter добавить поле approved: boolean (это значит подтверждена или нет инфа о животном (наверное) и в зависимости от этого в таблице строчка животного серого или черного цвета)

**Comment by Popov-Dmitriy-Ivanovich** [comment]
Какой у этой задачи приоритет?

**Comment by Popov-Dmitriy-Ivanovich** [comment]
файл cow_backend/server/routes/cows/filter.go  

В нем описаны 2 неприлично больших функции:   
- 1-ая - SerializeByFilter(...), 
- вторая не интересна.
в функции SerealizeByFilter(...) создается объект, который потом будет отправлен на фронтенд (рут /api/cows/filter)
в этот объект нужно добавить bool поле approved, которое true, если в параметре c (*models.Cow) поле approved отлично от нуля, иначе false
